name: Latest Essays workflow
on:
  schedule:
    - cron: '0 5 * * *' # Runs every day at 5 am
  workflow_dispatch:
jobs:
  update-readme-with-essays:
    name: Update this repo's README with latest writing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: MEDIUM-LIST
          commit_message: "Updated README.md with the latest writing"
          feed_list: "https://medium.com/feed/@amaanraazi"